services:
  bible:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./bible/:/app/
    #environment:
    #  - OPENAI_API_KEY=$OPENAI_API_KEY
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    command: "npx shadow-cljs watch app"

