services:
  bible:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./bible/:/app/
    #environment:
    #  - OPENAI_API_KEY=$OPENAI_API_KEY
    #ports:
    #  - "61799:61799"
    tty: true
    stdin_open: true
    #command: "lein repl :start :host 0.0.0.0 :port 61799"

